name: ci

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-24.04
    steps:

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/arm64
          push: true
          tags: ghcr.io/corvad/p3_s3:latest
          cache-from: type=registry,ref=corvad/p3_s3:buildcache
          cache-to: type=registry,ref=corvad/p3_s3:buildcache,mode=max
